# Generated by Django 5.2.7 on 2025-10-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_page_image_comment_page_alter_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='15 October 2025', max_length=100),
        ),
    ]
