# Generated by Django 5.2.7 on 2025-10-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='page',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commenthistory',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commenthistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='page',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pagepermission',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagepermission',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentHistory',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PagePermission',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
